Config = {}

Config.CinematicPeds = {
    {id = 1, label = "Garde de sécurité - Debout", model = "s_m_m_security_01", scenario = "WORLD_HUMAN_GUARD_STAND"},
    {id = 2, label = "Homme d'affaires - Téléphone", model = "s_m_m_businessman_01", scenario = "WORLD_HUMAN_STAND_MOBILE"},
    {id = 3, label = "Policier - Patrouille", model = "s_m_y_cop_01", scenario = "WORLD_HUMAN_COP_IDLES"},
    {id = 4, label = "Médecin - Debout", model = "s_m_m_doctor_01", scenario = "WORLD_HUMAN_CLIPBOARD"},
    {id = 5, label = "Pompier - Repos", model = "s_m_y_fireman_01", scenario = "WORLD_HUMAN_STAND_IMPATIENT"},
    {id = 6, label = "Mécanicien - Fume", model = "s_m_y_construct_01", scenario = "WORLD_HUMAN_SMOKING"},
    {id = 7, label = "Serveur - Service", model = "s_m_m_waiter_01", scenario = "WORLD_HUMAN_CLIPBOARD"},
    {id = 8, label = "Scientifique - Recherche", model = "s_m_m_scientist_01", scenario = "WORLD_HUMAN_CLIPBOARD"},
    {id = 9, label = "Agent FBI - Surveillance", model = "s_m_m_fibsec_01", scenario = "WORLD_HUMAN_STAND_IMPATIENT"},
    {id = 10, label = "Pilote - Debout", model = "s_m_m_pilot_01", scenario = "WORLD_HUMAN_STAND_MOBILE"},
    {id = 11, label = "Militaire - Garde", model = "s_m_y_marine_01", scenario = "WORLD_HUMAN_GUARD_STAND"},
    {id = 12, label = "Chirurgien - Opération", model = "s_m_m_paramedic_01", scenario = "WORLD_HUMAN_CLIPBOARD"},
    {id = 13, label = "Avocat - Téléphone", model = "s_m_m_lawyer_01", scenario = "WORLD_HUMAN_STAND_MOBILE"},
    {id = 14, label = "Banquier - Debout", model = "s_m_m_banker_01", scenario = "WORLD_HUMAN_CLIPBOARD"},
    {id = 15, label = "Chef cuisinier - Cuisine", model = "s_m_m_chef_01", scenario = "WORLD_HUMAN_CLIPBOARD"},
    {id = 16, label = "Agent immobilier - Visite", model = "s_m_m_highsec_01", scenario = "WORLD_HUMAN_STAND_MOBILE"},
    {id = 17, label = "Technicien - Réparation", model = "s_m_y_airworker_01", scenario = "WORLD_HUMAN_WELDING"},
    {id = 18, label = "Barman - Service", model = "s_m_m_barman_01", scenario = "WORLD_HUMAN_STAND_IMPATIENT"},
    {id = 19, label = "Vendeur de drogue - Deal", model = "g_m_y_mexgoon_01", scenario = "WORLD_HUMAN_DRUG_DEALER"},
    {id = 20, label = "Gangster - Menace", model = "g_m_y_famca_01", scenario = "WORLD_HUMAN_SMOKING"},
    {id = 21, label = "Vagabond - Assis", model = "a_m_m_tramp_01", scenario = "WORLD_HUMAN_BUM_STANDING"},
    {id = 22, label = "Femme d'affaires - Téléphone", model = "s_f_m_shop_high", scenario = "WORLD_HUMAN_STAND_MOBILE"},
    {id = 23, label = "Infirmière - Soins", model = "s_f_y_scrubs_01", scenario = "WORLD_HUMAN_CLIPBOARD"},
    {id = 24, label = "Agent de bord - Accueil", model = "s_f_y_airhostess_01", scenario = "WORLD_HUMAN_STAND_IMPATIENT"},
    {id = 25, label = "Danseuse - Strip club", model = "s_f_y_stripper_01", scenario = "WORLD_HUMAN_STRIP_WATCH_STAND"},
    {id = 26, label = "Prostituée - Rue", model = "s_f_y_hooker_01", scenario = "WORLD_HUMAN_PROSTITUTE_HIGH_CLASS"},
    {id = 27, label = "Actrice - Photo", model = "a_f_m_bevhills_01", scenario = "WORLD_HUMAN_STAND_MOBILE"},
    {id = 28, label = "Touriste - Photo", model = "a_f_y_tourist_01", scenario = "WORLD_HUMAN_TOURIST_MOBILE"},
    {id = 29, label = "Joggeuse - Repos", model = "a_f_y_runner_01", scenario = "WORLD_HUMAN_JOG_STANDING"},
    {id = 30, label = "Cycliste - Arrêt", model = "a_m_y_roadcyc_01", scenario = "WORLD_HUMAN_STAND_IMPATIENT"},
    {id = 31, label = "Hippie - Guitare", model = "a_m_m_hillbilly_01", scenario = "WORLD_HUMAN_MUSICIAN"},
    {id = 32, label = "Motard - Repos", model = "g_m_y_lost_01", scenario = "WORLD_HUMAN_SMOKING"},
    {id = 33, label = "Prisonnier - Debout", model = "s_m_y_prisoner_01", scenario = "WORLD_HUMAN_STAND_IMPATIENT"},
    {id = 34, label = "Ouvrier du bâtiment - Pause", model = "s_m_y_construct_02", scenario = "WORLD_HUMAN_SMOKING"},
    {id = 35, label = "Facteur - Livraison", model = "s_m_m_postal_01", scenario = "WORLD_HUMAN_CLIPBOARD"},
    {id = 36, label = "Éboueur - Travail", model = "s_m_y_garbage_01", scenario = "WORLD_HUMAN_JANITOR"},
    {id = 37, label = "Livreur - Colis", model = "s_m_m_ups_01", scenario = "WORLD_HUMAN_CLIPBOARD"},
    {id = 38, label = "Agent NOOSE - Tactique", model = "s_m_y_swat_01", scenario = "WORLD_HUMAN_GUARD_STAND"}
}
